# Generated by Django 2.0.3 on 2019-01-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=100)),
                ('valor_unidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao_unidade', models.CharField(max_length=200)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(max_length=15)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
    ]
