# Generated by Django 2.0.3 on 2019-01-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'ordering': ('descricao',)},
        ),
    ]
