# Generated by Django 2.0.3 on 2019-01-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('cnpj',),
            },
        ),
    ]
