# Generated by Django 2.0.3 on 2019-01-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190105_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='nome_empresa',
        ),
    ]
